import { CardGame, Footer, Nav } from "@/components";
import Head from "next/head";
import { Swiper, SwiperSlide } from "swiper/react";
import {
  Autoplay,
  EffectCoverflow,
  Navigation,
  Pagination
} from "swiper/modules";
import "swiper/css/navigation";
import "swiper/css/effect-coverflow";
import "swiper/css/pagination";
import { FaPaperPlane } from "react-icons/fa";

const Index = () => {
  return (
    <>
      <Head>
        <title>kitatopup</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div>
        <Nav />

        <div className="">
          <Swiper
            spaceBetween={50}
            slidesPerView={1}
            onSlideChange={() => console.log("slide change")}
            onSwiper={(swiper) => console.log(swiper)}
            modules={[Navigation]}
            className="h-screen bg-[#222232]"
          >
            <SwiperSlide>
              <div className="flex text-white relative">
                <div className="ps-28 z-40">
                  <h1 className="text-7xl w-[50%] font-medium mt-28 mb-6">
                    Topup Termurah hanya di Akita Topup
                  </h1>
                  <p className="text-lg opacity-75">
                    Kemudahan Top Up Game dengan
                    <br /> Akita TopUp: Bayar Mudah, Isi Ulang Cepat, Harga
                    Terjangkau!
                  </p>
                  <button className="text-xl flex items-center bg-gradient-to-r from-[#DC39FC] to-[#6244EC] px-8 py-3 rounded-full mt-12">
                    <FaPaperPlane className="me-3" /> explore
                  </button>
                </div>
                <div className="w-full absolute">
                  <img
                    className="w-[100em] opacity-70 transition delay-1000"
                    src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/a44778ea-3457-40e0-8979-b7e3685d23d0/dfas4gh-d969d143-d63b-4620-8dba-9c7b6aa3f55e.png/v1/fill/w_1280,h_720/sun_wicked_flames_collector_skin_8k_png_by_newjer53_dfas4gh-fullview.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NzIwIiwicGF0aCI6IlwvZlwvYTQ0Nzc4ZWEtMzQ1Ny00MGUwLTg5NzktYjdlMzY4NWQyM2QwXC9kZmFzNGdoLWQ5NjlkMTQzLWQ2M2ItNDYyMC04ZGJhLTljN2I2YWEzZjU1ZS5wbmciLCJ3aWR0aCI6Ijw9MTI4MCJ9XV0sImF1ZCI6WyJ1cm46c2VydmljZTppbWFnZS5vcGVyYXRpb25zIl19.TTnyckQMuOKs6FVwhKPdRmsjk3FVpnkLJXz7AdxL5-Q"
                  />
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>Slide 2</SwiperSlide>
          </Swiper>
        </div>
        <div className="bg-gradient-to-r from-[#DC39FC] to-[#6244EC] px-28 py-10 flex space-x-3">
          <div className="w-fit px-8 py-4 border-[1px] border-white rounded-full text-white">
            <p>Lagi Populer</p>
          </div>
          <div className="w-fit px-8 py-4 border-[1px] border-white rounded-full text-white">
            <p>Baru Liris</p>
          </div>
        </div>
        <div className="min-h-screen bg-gradient-to-r from-[#222232] to-[#393d47] pt-16 px-28">
          <h2 className="text-white text-5xl font-semibold">Paling Laris</h2>
          <p className="text-[#A2A0A9] mt-4 mb-8">Most Popular TopUp</p>
          <Swiper
            effect={"coverflow"}
            grabCursor={true}
            centeredSlides={true}
            slidesPerView={3}
            coverflowEffect={{
              rotate: 75,
              stretch: 40,
              depth: 0,
              modifier: 1
            }}
            autoplay={{
              delay: 2500,
              disableOnInteraction: false
            }}
            pagination={true}
            modules={[EffectCoverflow, Pagination, Autoplay]}
            className="w-[70%]"
          >
            <SwiperSlide>
              <CardGame />
            </SwiperSlide>
            <SwiperSlide>
              <CardGame />
            </SwiperSlide>
            <SwiperSlide>
              <CardGame />
            </SwiperSlide>
            <SwiperSlide>
              <CardGame />
            </SwiperSlide>
            <SwiperSlide>
              <CardGame />
            </SwiperSlide>
            <SwiperSlide>
              <CardGame />
            </SwiperSlide>
          </Swiper>
        </div>

        <div className="min-h-screen bg-[#14161B] pt-16 px-28">
          <h2 className="text-white text-5xl font-semibold">
            Baru diTambahkan
          </h2>
          <p className="text-[#A2A0A9] mt-4">New release</p>
          <div className="mt-8 grid grid-cols-3">
            <CardGame />
            <CardGame />
          </div>
        </div>
      </div>

      <div>
        <Footer />
      </div>
    </>
  );
};

export default Index;
